// Copyright (c) 2025-present Polymath Robotics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once

#include <vector>

#include "behaviortree_cpp/bt_factory.h"

namespace BT
{
using PluginRegisterFunction = void (*)(BT::BehaviorTreeFactory &);

/// @brief Forward declare this function to get a global registration function list,
/// which must be implemented in plugin loader libraries.
/// This is autogenerated by the AutoPluginRegistrar created by the CMake macros.
std::vector<PluginRegisterFunction> & get_plugin_register_functions();
}  // namespace BT

/// @brief Implementation detail for plugin registration.
/// @details
/// Generates a static registration function,
/// a uniquely named struct in an anonymous namespace,
/// and creates an instance of that struct in place.
/// The constructor of the struct is called by the static instance, which is created on loading the library.
/// That constructor adds the plugin registration function to a static global vector that is declared here,
/// but defined by autogenerated code in plugin provider libraries.
/// Automatically filling that vector of plugin registration functions is the end result of these macros.
#define BT_PLUGIN_REGISTER_IMPL(factory_param, UniqueID)                                 \
  static void bt_plugin_register_fn_##UniqueID(BT::BehaviorTreeFactory & factory_param); \
  namespace                                                                              \
  {                                                                                      \
  struct bt_plugin_register_struct_##UniqueID                                            \
  {                                                                                      \
    bt_plugin_register_struct_##UniqueID()                                               \
    {                                                                                    \
      BT::get_plugin_register_functions().push_back(&bt_plugin_register_fn_##UniqueID);  \
    }                                                                                    \
  } bt_plugin_register_instance_##UniqueID;                                              \
  }                                                                                      \
  static void bt_plugin_register_fn_##UniqueID(BT::BehaviorTreeFactory & factory_param)

#define BT_PLUGIN_REGISTER_HOP1(factory_param, UniqueID) BT_PLUGIN_REGISTER_IMPL(factory_param, UniqueID)

/// @brief Arbitrarily modify the BehaviorTreeFactory at will by providing a function body
/// @param factory_param The name that the factory will be given to you as
/// @example
/// BT_PLUGIN_REGISTER(factory)
/// {
///   factory.registerNodeType<my_node_namespace::MyNode>("MyNode");
/// }
#define BT_PLUGIN_REGISTER(factory_param) BT_PLUGIN_REGISTER_HOP1(factory_param, __COUNTER__)

/// @brief Call this macro to register a single BT Node with as little boilerplate as possible
/// @param node_name The name that the exposed BT node will be used by, e.g. <node_name>
/// @param node_class The fully qualified class name that implements the node, e.g. my_namespace::MyNodeClass
#define BT_PLUGIN_REGISTER_NODE(node_name, node_class) \
  BT_PLUGIN_REGISTER(factory)                          \
  {                                                    \
    factory.registerNodeType<node_class>(#node_name);  \
  }
