---
name: Build and test
"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros: [humble, jazzy, kilted, rolling]
        package: [behaviortree_cpp_pluginlib, behaviortree_cpp_pluginlib_tests]
        include:
          - ros: humble
            ubuntu: jammy
          - ros: jazzy
            ubuntu: noble
          - ros: kilted
            ubuntu: noble-testing
          - ros: rolling
            ubuntu: noble
    name: ${{ matrix.ros }} - ${{ matrix.package }}
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-${{ matrix.ubuntu }}:latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: ${{ matrix.ros }}
          package-name: ${{ matrix.package }}
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs__${{ matrix.package }}__${{ matrix.ros }}
          path: ros_ws/log
